name: local_bus
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dropdown_search: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  carousel_pro: ^1.0.0
  url_launcher: ^6.0.3
  share: ^2.0.4
  google_maps_flutter: ^2.0.10
  location: ^4.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/